name: superpong
description: A super pong game made with Flutter & Flame.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flame: ^1.2.0
  flame_audio: ^1.3.2
  flame_behaviors: ^0.1.0
  flame_gamepad: ^0.0.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  get_it: ^7.2.0
  mobx: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.0
  mobx_codegen: ^2.0.7+3
  flame_test: ^1.5.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
flutter:
  assets:
    - assets/audio/music/bg_music.ogg
    - assets/audio/sfx/fire_1.mp3
    - assets/audio/sfx/fire_2.mp3